crud-product_index:
    path:     /
    defaults: { _controller: "NeklesaStoreBundle:Product:index" }
    methods:  GET

crud-product_show:
    path:     /{id}/show
    defaults: { _controller: "NeklesaStoreBundle:Product:show" }
    methods:  GET

crud-product_new:
    path:     /new
    defaults: { _controller: "NeklesaStoreBundle:Product:new" }
    methods:  [GET, POST]

crud-product_edit:
    path:     /{id}/edit
    defaults: { _controller: "NeklesaStoreBundle:Product:edit" }
    methods:  [GET, POST]

crud-product_delete:
    path:     /{id}/delete
    defaults: { _controller: "NeklesaStoreBundle:Product:delete" }
    methods:  DELETE
